[package]
name = "time_track_cli"
version = "0.1.0"
authors = ["Lukas Orsvärn <lukas@orsvarn.com>"]

[dependencies]
chrono = "0.4"
clap = "2.31"
directories = "0.10"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
time_track = { git = "https://github.com/lukors/time_track" }
